# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_uploads/article_images/', verbose_name='Фото статьи'),
        ),
    ]
