# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20170722_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='Изображение статьи'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('creator', 'title')]),
        ),
    ]
