# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментаторы'},
        ),
    ]
