# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_uploads/accessories/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_uploads/bag/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Сумка',
                'verbose_name_plural': 'Сумки',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_uploads/bike/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
            },
        ),
        migrations.CreateModel(
            name='CustomSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_uploads/custom_seat/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Стандартное седло',
                'verbose_name_plural': 'Стандартные седла',
            },
        ),
        migrations.CreateModel(
            name='LeatherSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_uploads/leather_seat/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Кожаное седло',
                'verbose_name_plural': 'Кожаные седла',
            },
        ),
        migrations.CreateModel(
            name='LimitedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_uploads/limited_seat/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Эксклюзивное седло',
                'verbose_name_plural': 'Эксклюзивные седла',
            },
        ),
    ]
