# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('male', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=128, null=True, verbose_name='Пол')),
                ('biography', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Биография')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/user_uploads/avatars/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Профайлы пользователей',
                'verbose_name': 'Профайл пользователя',
                'abstract': False,
            },
        ),
    ]
