# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_uploads/avatars/', verbose_name='Фото'),
        ),
    ]
